/**
 * @file web_server.c
 * @brief Implementation of HTTP provisioning portal, NVS credential validation, 
 *        defensive URL parsing, and robust error handling for ESP32 with LED status integration.
 */

#include "web_server.h"
#include "network_manager.h"
#include "nvs_manager.h"
#include "led_manager.h"
#include "esp_http_server.h"
#include "esp_log.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include <string.h>
#include <stdlib.h>
#include <sys/socket.h>
#include <netdb.h>
#include <arpa/inet.h>

/// Logging tag for Web Server module
static const char *TAG = "WEB_SRV";

/// Active HTTP server instance handle
static httpd_handle_t s_server = NULL;

/// NVS storage namespace for configuration parameters
#define NVS_NAMESPACE "storage"

/* Embedded frontend file references generated by CMake EMBED_FILES directive */
extern const char index_html_start[] asm("_binary_index_html_start");
extern const char index_html_end[]   asm("_binary_index_html_end");

/**
 * @typedef wifi_config_params_t
 * @brief Struct layout to pass submitted credentials safely to the background worker task.
 */
typedef struct {
    char ssid[32];
    char password[64];
    char bms_type[16];
    char mqtt_uri[128];
} wifi_config_params_t;

// Forward declarations of internal static routines
static esp_err_t start_http_server(void);
static void wifi_test_task(void *pvParameters);

/**
 * @brief Safely sanitizes and URL-decodes percent-encoded URIs with buffer overflow protection.
 * 
 * @param src_uri Source encoded string.
 * @param dest_uri Destination buffer for decoded output.
 * @param max_len Maximum size of destination buffer.
 */
static void sanitize_uri(const char *src_uri, char *dest_uri, size_t max_len)
{
    if (src_uri == NULL || dest_uri == NULL || max_len == 0) return;

    size_t src = 0, dst = 0;
    while (src_uri[src] != '\0' && dst < max_len - 1) {
        if (src_uri[src] == '%' && src_uri[src+1] != '\0' && src_uri[src+2] != '\0') {
            char hex[3] = {src_uri[src+1], src_uri[src+2], '\0'};
            char *endptr = NULL;
            long decoded_char = strtol(hex, &endptr, 16);
            
            if (endptr == hex + 2) {
                dest_uri[dst++] = (char)decoded_char;
                src += 3;
            } else {
                dest_uri[dst++] = src_uri[src++];
            }
        } else {
            dest_uri[dst++] = src_uri[src++];
        }
    }
    dest_uri[dst] = '\0';
}

/**
 * @brief Helper function to test TCP connectivity to an MQTT broker URI securely.
 */
static bool test_mqtt_reachability(const char *uri)
{
    if (uri == NULL || strlen(uri) == 0) return false;

    char clean_uri[128] = {0};
    char host[64] = {0};
    int port = 1883;

    sanitize_uri(uri, clean_uri, sizeof(clean_uri));

    const char *p = clean_uri;
    if (strncmp(p, "mqtts://", 8) == 0) {
        p += 8;
        port = 8883; // Secure MQTT default port
    } else if (strncmp(p, "mqtt://", 7) == 0) {
        p += 7;
    }

    const char *colon = strchr(p, ':');
    if (colon) {
        size_t host_len = colon - p;
        if (host_len < sizeof(host)) {
            memcpy(host, p, host_len);
            host[host_len] = '\0';
        }
        port = atoi(colon + 1);
    } else {
        const char *slash = strchr(p, '/');
        if (slash) {
            size_t host_len = slash - p;
            if (host_len < sizeof(host)) {
                memcpy(host, p, host_len);
                host[host_len] = '\0';
            }
        } else {
            strncpy(host, p, sizeof(host) - 1);
        }
    }

    if (strlen(host) == 0) return false;

    ESP_LOGI(TAG, "Testing MQTT broker reachability -> Host: %s, Port: %d", host, port);

    struct sockaddr_in dest_addr;
    memset(&dest_addr, 0, sizeof(dest_addr));
    dest_addr.sin_family = AF_INET;
    dest_addr.sin_port = htons(port);
    
    struct hostent *he = gethostbyname(host);
    if (he == NULL || he->h_addr == NULL) {
        ESP_LOGE(TAG, "Failed to resolve MQTT broker hostname: %s", host);
        return false;
    }
    memcpy(&dest_addr.sin_addr, he->h_addr, he->h_length);

    int sock = socket(AF_INET, SOCK_STREAM, IPPROTO_IP);
    if (sock < 0) return false;

    struct timeval timeout = { .tv_sec = 2, .tv_usec = 0 };
    setsockopt(sock, SOL_SOCKET, SO_RCVTIMEO, &timeout, sizeof(timeout));
    setsockopt(sock, SOL_SOCKET, SO_SNDTIMEO, &timeout, sizeof(timeout));

    int err = connect(sock, (struct sockaddr *)&dest_addr, sizeof(dest_addr));
    close(sock);

    if (err != 0) {
        ESP_LOGW(TAG, "MQTT broker is unreachable (err: %d).", err);
        return false;
    }

    ESP_LOGI(TAG, "MQTT broker is online and reachable.");
    return true;
}

/**
 * @brief HTTP GET request handler for root endpoint "/". Serves the embedded configuration portal HTML.
 */
static esp_err_t index_get_handler(httpd_req_t *req)
{
    if (req == NULL) return ESP_ERR_INVALID_ARG;

    httpd_resp_set_type(req, "text/html");
    size_t html_len = index_html_end - index_html_start;
    return httpd_resp_send(req, index_html_start, html_len);
}

/**
 * @brief Background worker task that executes connection testing without blocking HTTP socket response threads.
 */
static void wifi_test_task(void *pvParameters)
{
    wifi_config_params_t *params = (wifi_config_params_t *)pvParameters;
    if (params == NULL) {
        vTaskDelete(NULL);
        return;
    }

    ESP_LOGI(TAG, "Testing connection to submitted SSID: %s", params->ssid);

    web_server_stop();

    bool is_connected = network_manager_test_sta_connection(params->ssid, params->password);

    if (is_connected) {
        ESP_LOGI(TAG, "Wi-Fi connected. Verifying MQTT broker accessibility...");
        
        bool is_mqtt_ok = (strlen(params->mqtt_uri) > 0) && test_mqtt_reachability(params->mqtt_uri);

        if (is_mqtt_ok) {
            ESP_LOGI(TAG, "SUCCESS: Wi-Fi & MQTT verified! Storing credentials into NVS storage...");
            
            char clean_mqtt_uri[128] = {0};
            sanitize_uri(params->mqtt_uri, clean_mqtt_uri, sizeof(clean_mqtt_uri));

            nvs_manager_write_str(NVS_NAMESPACE, "wifi_ssid", params->ssid);
            nvs_manager_write_str(NVS_NAMESPACE, "wifi_pass", params->password);
            nvs_manager_write_str(NVS_NAMESPACE, "bms_type", params->bms_type);
            nvs_manager_write_str(NVS_NAMESPACE, "mqtt_uri", clean_mqtt_uri);

            // Verification successful: Switch LED to normal operation mode
            led_manager_set_mode(LED_MODE_OFF);

            ESP_LOGI(TAG, "Configuration saved successfully. Rebooting device to apply new BMS and network settings...");
            vTaskDelay(pdMS_TO_TICKS(1000));
            esp_restart();
        } else {
            ESP_LOGW(TAG, "WARNING: MQTT broker unreachable. Restoring AP provisioning portal...");
            is_connected = false;
        }
    }

    if (!is_connected) {
        ESP_LOGE(TAG, "FAILURE: Connection check failed. Restoring AP provisioning portal...");
        led_manager_set_mode(LED_MODE_ERROR);
        vTaskDelay(pdMS_TO_TICKS(1000));

        network_manager_start_ap();
        led_manager_set_mode(LED_MODE_PROVISIONING); // Re-entered AP mode, fast blink
        vTaskDelay(pdMS_TO_TICKS(200));
        start_http_server();
    }

    vPortFree(params);
    vTaskDelete(NULL);
}

/**
 * @brief HTTP POST request handler for endpoint "/save". Parses form-urlencoded data safely and spawns verification task.
 */
static esp_err_t save_post_handler(httpd_req_t *req)
{
    if (req == NULL) return ESP_ERR_INVALID_ARG;

    char buf[384];
    int remaining = req->content_len;

    if (remaining <= 0 || remaining >= sizeof(buf)) {
        httpd_resp_send_500(req);
        return ESP_FAIL;
    }

    int ret = httpd_req_recv(req, buf, remaining);
    if (ret <= 0) {
        httpd_resp_send_500(req);
        return ESP_FAIL;
    }
    buf[ret] = '\0';

    wifi_config_params_t *params = pvPortMalloc(sizeof(wifi_config_params_t));
    if (params == NULL) {
        ESP_LOGE(TAG, "Failed to allocate memory for wifi_config_params_t");
        httpd_resp_send_500(req);
        return ESP_ERR_NO_MEM;
    }
    memset(params, 0, sizeof(wifi_config_params_t));

    httpd_query_key_value(buf, "ssid", params->ssid, sizeof(params->ssid));
    httpd_query_key_value(buf, "pass", params->password, sizeof(params->password));
    httpd_query_key_value(buf, "bms", params->bms_type, sizeof(params->bms_type));
    httpd_query_key_value(buf, "mqtt_uri", params->mqtt_uri, sizeof(params->mqtt_uri));

    ESP_LOGI(TAG, "Configuration payload received - SSID: %s, BMS: %s, MQTT URI: %s", 
             params->ssid, params->bms_type, params->mqtt_uri);

    const char* success_resp = "<html><body style='font-family:Arial; text-align:center; padding-top:50px;'>" \
                               "<h2 style='color:green;'>Configuration Received! Testing Wi-Fi & MQTT...</h2>" \
                               "</body></html>";
    httpd_resp_set_type(req, "text/html");
    httpd_resp_send(req, success_resp, HTTPD_RESP_USE_STRLEN);

    if (xTaskCreate(wifi_test_task, "wifi_test_task", 4096, params, 5, NULL) != pdPASS) {
        ESP_LOGE(TAG, "Failed to create wifi_test_task!");
        vPortFree(params);
        return ESP_FAIL;
    }

    return ESP_OK;
}

/**
 * @brief Starts the HTTP configuration web server.
 */
static esp_err_t start_http_server(void)
{
    httpd_config_t config = HTTPD_DEFAULT_CONFIG();
    config.max_uri_handlers = 4;

    ESP_LOGI(TAG, "Starting HTTP configuration daemon on port %d...", config.server_port);
    if (httpd_start(&s_server, &config) == ESP_OK) {
        httpd_uri_t uri_index = {
            .uri      = "/",
            .method   = HTTP_GET,
            .handler  = index_get_handler,
            .user_ctx = NULL
        };
        httpd_register_uri_handler(s_server, &uri_index);

        httpd_uri_t uri_save = {
            .uri      = "/save",
            .method   = HTTP_POST,
            .handler  = save_post_handler,
            .user_ctx = NULL
        };
        httpd_register_uri_handler(s_server, &uri_save);

        return ESP_OK;
    }
    return ESP_FAIL;
}

/**
 * @brief Initializes the provisioning portal, validates NVS credentials and MQTT reachability.
 */
esp_err_t web_server_init_portal(void)
{
    char ssid[32] = {0};
    char password[64] = {0};
    char mqtt_uri[128] = {0};

    nvs_manager_read_str(NVS_NAMESPACE, "wifi_ssid", ssid, sizeof(ssid), "");
    nvs_manager_read_str(NVS_NAMESPACE, "wifi_pass", password, sizeof(password), "");
    nvs_manager_read_str(NVS_NAMESPACE, "mqtt_uri", mqtt_uri, sizeof(mqtt_uri), "");

    if (strlen(ssid) > 0) {
        ESP_LOGI(TAG, "Retrieved valid NVS credentials for SSID: %s. Initiating router handshake...", ssid);

        bool is_wifi_connected = network_manager_test_sta_connection(ssid, password);

        if (is_wifi_connected) {
            ESP_LOGI(TAG, "Wi-Fi connected. Verifying MQTT broker reachability: %s", mqtt_uri);
            
            bool is_mqtt_reachable = (strlen(mqtt_uri) > 0) && test_mqtt_reachability(mqtt_uri);

            if (is_mqtt_reachable) {
                ESP_LOGI(TAG, "SUCCESS: Authenticated via stored NVS credentials & MQTT verified. Portal bypassed.");
                led_manager_set_mode(LED_MODE_OFF); // Successful boot, normal mode
                return ESP_OK;
            } else {
                ESP_LOGW(TAG, "WARNING: Stored MQTT broker is unreachable. Falling back to AP provisioning mode.");
            }
        } else {
            ESP_LOGW(TAG, "WARNING: Stored Wi-Fi credential validation failed. Falling back to AP provisioning mode.");
        }
    } else {
        ESP_LOGI(TAG, "NOTICE: No active credentials found in non-volatile storage partition.");
    }

    ESP_LOGI(TAG, "Activating Access Point mode and launching configuration web server...");
    ESP_ERROR_CHECK(network_manager_start_ap());
    ESP_ERROR_CHECK(start_http_server());
    
    // AP provisioning mode active, start fast blinking on status LED
    led_manager_set_mode(LED_MODE_PROVISIONING);

    return ESP_OK;
}

/**
 * @brief Stops and cleans up the active HTTP configuration server instance.
 */
esp_err_t web_server_stop(void)
{
    if (s_server != NULL) {
        ESP_LOGI(TAG, "Stopping active HTTP server instance...");
        httpd_stop(s_server);
        s_server = NULL;
    }
    return ESP_OK;
}