/**
 * @file web_server.c
 * @brief Implementation of HTTP provisioning portal, NVS credential validation, and dynamic component orchestration.
 */

#include "web_server.h"
#include "network_manager.h"
#include "nvs_manager.h"
#include "esp_http_server.h"
#include "esp_log.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include <string.h>

static const char *TAG = "WEB_SRV";
static httpd_handle_t s_server = NULL;

#define NVS_NAMESPACE "storage"

/* Embedded frontend file references generated by CMake EMBED_FILES directive */
extern const char index_html_start[] asm("_binary_index_html_start");
extern const char index_html_end[]   asm("_binary_index_html_end");

/**
 * @typedef wifi_config_params_t
 * @brief Struct layout to pass submitted Wi-Fi credentials safely to the background worker task.
 */
typedef struct {
    char ssid[32];
    char password[64];
    char bms_type[16];
} wifi_config_params_t;

// Forward declarations of internal static routines
static esp_err_t start_http_server(void);
static void wifi_test_task(void *pvParameters);

/**
 * @brief HTTP GET request handler for root endpoint "/". Serves the embedded configuration portal HTML.
 * 
 * @param req Pointer to HTTP request structure.
 * @return esp_err_t ESP_OK on successful transmission.
 */
static esp_err_t index_get_handler(httpd_req_t *req)
{
    httpd_resp_set_type(req, "text/html");
    size_t html_len = index_html_end - index_html_start;
    httpd_resp_send(req, index_html_start, html_len);
    return ESP_OK;
}

/**
 * @brief Background worker task that executes connection testing without blocking HTTP socket response threads.
 *        Persists credentials to NVS upon success or restores AP mode and web portal upon failure.
 * 
 * @param pvParameters Pointer to dynamically allocated wifi_config_params_t payload.
 */
static void wifi_test_task(void *pvParameters)
{
    wifi_config_params_t *params = (wifi_config_params_t *)pvParameters;

    ESP_LOGI(TAG, "Testing connection to submitted SSID: %s", params->ssid);

    // Temporarily shutdown HTTP server to release port 80 socket bindings during Wi-Fi mode transitions
    web_server_stop();

    // Execute synchronous router handshaking via network manager
    bool is_connected = network_manager_test_sta_connection(params->ssid, params->password);

    if (is_connected) {
        ESP_LOGI(TAG, "SUCCESS: Connected to router! Storing credentials into NVS storage...");
        
        // Persist SSID, password, and BMS selection into NVS partition under designated namespace
        nvs_manager_write_str(NVS_NAMESPACE, "wifi_ssid", params->ssid);
        nvs_manager_write_str(NVS_NAMESPACE, "wifi_pass", params->password);
        nvs_manager_write_str(NVS_NAMESPACE, "bms_type", params->bms_type);

        ESP_LOGI(TAG, "Credentials secured. Device will operate in Station (STA) mode.");
    } else {
        ESP_LOGE(TAG, "FAILURE: Connection attempt timed out or rejected. Restoring AP provisioning portal...");
        
        // Re-enable Access Point mode and restart web server configuration interface for user retry
        network_manager_start_ap();
        vTaskDelay(pdMS_TO_TICKS(200)); // Stabilization delay for network driver
        start_http_server();
    }

    // Free heap memory allocated for parameters and delete current FreeRTOS task instance
    vPortFree(params);
    vTaskDelete(NULL);
}

/**
 * @brief HTTP POST request handler for endpoint "/save". Parses form-urlencoded data and spawns verification task.
 * 
 * @param req Pointer to HTTP request structure.
 * @return esp_err_t ESP_OK on successful request acceptance.
 */
static esp_err_t save_post_handler(httpd_req_t *req)
{
    char buf[256];
    int ret, remaining = req->content_len;

    if (remaining >= sizeof(buf)) {
        httpd_resp_send_500(req);
        return ESP_FAIL;
    }

    ret = httpd_req_recv(req, buf, remaining);
    if (ret <= 0) {
        return ESP_FAIL;
    }
    buf[ret] = '\0';

    wifi_config_params_t *params = pvPortMalloc(sizeof(wifi_config_params_t));
    if (params == NULL) {
        httpd_resp_send_500(req);
        return ESP_FAIL;
    }

    httpd_query_key_value(buf, "ssid", params->ssid, sizeof(params->ssid));
    httpd_query_key_value(buf, "pass", params->password, sizeof(params->password));
    httpd_query_key_value(buf, "bms", params->bms_type, sizeof(params->bms_type));

    ESP_LOGI(TAG, "Configuration payload received - SSID: %s, BMS Type: %s", params->ssid, params->bms_type);

    // Send immediate HTML feedback to browser before initiating blocking connection routines
    const char* success_resp = "<html><body style='font-family:Arial; text-align:center; padding-top:50px;'>" \
                               "<h2 style='color:green;'>Configuration Received! Testing Connection...</h2>" \
                               "</body></html>";
    httpd_resp_set_type(req, "text/html");
    httpd_resp_send(req, success_resp, HTTPD_RESP_USE_STRLEN);

    // Create asynchronous FreeRTOS worker task to handle network handshaking safely
    xTaskCreate(wifi_test_task, "wifi_test_task", 4096, params, 5, NULL);

    return ESP_OK;
}

/**
 * @brief Initializes and starts the lightweight LwIP HTTP web server daemon.
 * 
 * @return esp_err_t ESP_OK on success, ESP_FAIL otherwise.
 */
static esp_err_t start_http_server(void)
{
    httpd_config_t config = HTTPD_DEFAULT_CONFIG();
    config.max_uri_handlers = 4;

    ESP_LOGI(TAG, "Starting HTTP configuration daemon on port %d...", config.server_port);
    if (httpd_start(&s_server, &config) == ESP_OK) {
        httpd_uri_t uri_index = {
            .uri      = "/",
            .method   = HTTP_GET,
            .handler  = index_get_handler,
            .user_ctx = NULL
        };
        httpd_register_uri_handler(s_server, &uri_index);

        httpd_uri_t uri_save = {
            .uri      = "/save",
            .method   = HTTP_POST,
            .handler  = save_post_handler,
            .user_ctx = NULL
        };
        httpd_register_uri_handler(s_server, &uri_save);

        return ESP_OK;
    }
    return ESP_FAIL;
}

esp_err_t web_server_init_portal(void)
{
    char ssid[32] = {0};
    char password[64] = {0};

    // 1. Query NVS storage layer for previously persisted router credentials
    nvs_manager_read_str(NVS_NAMESPACE, "wifi_ssid", ssid, sizeof(ssid), "");
    nvs_manager_read_str(NVS_NAMESPACE, "wifi_pass", password, sizeof(password), "");

    if (strlen(ssid) > 0) {
        ESP_LOGI(TAG, "Retrieved valid NVS credentials for SSID: %s. Initiating router handshake...", ssid);

        // 2. Validate stored credentials by attempting synchronous connection
        bool is_connected = network_manager_test_sta_connection(ssid, password);

        if (is_connected) {
            ESP_LOGI(TAG, "SUCCESS: Authenticated via stored NVS credentials. Provisioning portal bypassed.");
            return ESP_OK;
        } else {
            ESP_LOGW(TAG, "WARNING: Stored credential validation failed. Falling back to AP provisioning mode.");
        }
    } else {
        ESP_LOGI(TAG, "NOTICE: No active credentials found in non-volatile storage partition.");
    }

    // 3. Fallback or initial boot path: Activate AP mode and HTTP configuration web portal
    ESP_LOGI(TAG, "Activating Access Point mode and launching configuration web server...");
    ESP_ERROR_CHECK(network_manager_start_ap());
    ESP_ERROR_CHECK(start_http_server());

    return ESP_OK;
}

esp_err_t web_server_stop(void)
{
    if (s_server) {
        ESP_LOGI(TAG, "Stopping active HTTP server instance...");
        httpd_stop(s_server);
        s_server = NULL;
    }
    return ESP_OK;
}